// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'healthai';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String HOME = 'assets/images/Home.svg';
  static const String ARTICLES = 'assets/images/articles.svg';
  static const String BANDAGE = 'assets/images/bandage.svg';
  static const String DUMBBELL = 'assets/images/dumbbell.svg';
  static const String MEDICAL_CONSULTATION =
      'assets/images/medical_consultation.svg';
  static const String NOTIFICATION = 'assets/images/notification.svg';
  static const String PROFILE2 = 'assets/images/profile2.svg';
  static const String THERMOMETER = 'assets/images/thermometer.svg';
}
